In [1]:
import torch

x = torch.arange(5).reshape((1,5))
y = torch.arange(3).reshape((3,1))

x,y

(tensor([[0, 1, 2, 3, 4]]),
 tensor([[0],
         [1],
         [2]]))

### 广播机制：
1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。

In [2]:
x + y

tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [18]:

try:
    x = torch.arange(24).reshape((3,8))
    y = torch.arange(24).reshape((8,3))
    print(x,y)
   
except RuntimeError as e:
    print(e)

# 三维只有有一个维度为1才能



tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]) tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])
